apiVersion: v1
kind: Service
metadata:
  name: summarize-svc
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30001
    targetPort: 5000
    protocol: TCP
  selector:
    app: summarize-text
